config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root 'situations#index'
    resources :situations do
      resources :metaphors
    end
  get   'users/:id'   =>  'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/metaphor.rb
class Metaphor < ApplicationRecord
  belongs_to :situation
  belongs_to :user
end

app/models/situation.rb
class Situation < ApplicationRecord
  has_many :metaphors
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :metaphors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/metaphors_controller.rb
class MetaphorsController < ApplicationController
    before_action :set_situation
    before_action :move_to_index, except: :index
    layout 'metaphors'

  def index
    @situation = Situation.find(params[:situation_id])
    @metaphors = @situation.metaphors.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
  end

  def create
    Metaphor.create(image: params[:image], text: params[:text], situation_id: @situation.id, user_id: current_user.id)
  end

  def destroy
      metaphor = Metaphor.find(params[:id])
      if metaphor.user_id == current_user.id
        metaphor.destroy
      end
  end

  def edit
    @metaphor = Metaphor.find(params[:id])
  end

  def update
      metaphor = Metaphor.find(params[:id])
      if metaphor.user_id == current_user.id
        metaphor.update(metaphor_params)
      end
  end

  private
  def metaphor_params
    params.permit(:image, :text)
  end

  def set_situation
    @situation = Situation.find(params[:situation_id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end


# def create
#       Tweet.create(name: tweet_params[:name], image: tweet_params[:image], text: tweet_params[:text], user_id: current_user.id)
#     end

#     private
#     def tweet_params
#       params.permit(:name, :image, :text)
#     end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @situations = Situation.includes(:metaphors).order("created_at DESC").page(params[:page]).per(5)
  end

  def new

  end

  def create
    Situation.create(situation_params)
  end

  private
  def situation_params
    params.permit( :image, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @nickname = current_user.nickname
      @metaphors = current_user.metaphors.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metaphors_helper.rb
module MetaphorsHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tatoeba</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Tatoeba</a></h1>
        <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "なにたとえる？", new_situation_path, class: 'post' %>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Tatoeba 2019.
      </p>
    </footer>
  </body>
</html>

app/views/layouts/metaphors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tatoeba</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Tatoeba</a></h1>
        <div class="user_nav grid-6">
          <%= link_to 'たとえてみよう!', "/situations/#{@situation.id}/metaphors/new", method: :get %>
          <!-- <a class="post" href="/situations/new">たとえてみよう！</a> -->
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Tatoeba 2019.
      </p>
    </footer>
  </body>
</html>

app/views/metaphors/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        素敵ですね！
      </h3>
      <a class="btn" href="/situations/<%= @situation.id%>/metaphors">一覧へ戻る</a>
    </div>
  </div>

app/views/metaphors/destroy.html.erb
 <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/situations/<%= @situation.id%>/metaphors">一覧へ戻る</a>
    </div>
  </div>

app/views/metaphors/edit.html.erb
<div class="contents row">
    <%= form_tag("/situations/#{@situation.id}/metaphors/#{@metaphor.id}", method: :patch ) do %>
      <h3>
        編集する
      </h3>
      <input placeholder="Image Url" type="text" name="image" value="<%= @metaphor.image %>" autofocus="true">
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @metaphor.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

<!-- /situations/#{@situation.id}/metaphors/#{@metaphor.id} -->

app/views/metaphors/index.html.erb
  <div class="contents row" >
    <% @metaphors.each do |metaphor| %>
      <div class="content_post" style="background-image: url(<%= metaphor.image %>);">
        <% if user_signed_in? && current_user.id == metaphor.user_id %>
        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
          <ul class="more_list">
            <li>
              <%= link_to '編集', "/situations/#{@situation.id}/metaphors/#{metaphor.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/situations/#{@situation.id}/metaphors/#{metaphor.id}", method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
        <%= simple_format(metaphor.text) %>
        <span class="name">
          <a href="">
            <span>投稿者</span><%= metaphor.user.nickname %>
          </a>
        </span>
      </div>
    <% end %>
    <%= paginate(@metaphors) %>
  </div>

app/views/metaphors/new.html.erb
<div class="contents row">
  <%= form_tag("/situations/#{@situation.id}/metaphors", method: :post) do %>
    <h3>
      たとえば？
    </h3>
    <input placeholder="Image Url" type="text" name="image">
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/metaphors/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/situations/<%= @situation.id%>/metaphors">たとえ一覧へ戻る</a>
    </div>
  </div>

app/views/situations/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        早速たとえてみよう！
      </h3>
      <a class="btn" href="/situations">一覧へ戻る</a>
    </div>
  </div>

app/views/situations/index.html.erb
  <div class="contents row" >
    <% @situations.each do |situation| %>
      <div class="content_post" style="background-image: url(<%= situation.image %>);">
        <a class="post" href="/situations/<%= situation.id %>/metaphors"><%= simple_format(situation.text) %></a>
      </div>
    <% end %>
    <%= paginate(@situations) %>
  </div>

app/views/situations/new.html.erb
<div class="contents row">
  <%= form_tag('/situations', method: :post) do %>
    <h3>
      なにたとえる？
    </h3>
    <input placeholder="Image Url" type="text" name="image">
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/users/show.html.erb
<div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @metaphors.each do |metaphor| %>
      <div class="content_post" style="background-image: url(<%= metaphor.image %>);">
        <%= simple_format(metaphor.text) %>
        <span class="name"><%= @nickname %></span>
      </div>
    <% end %>
    <%= paginate(@metaphors) %>
  </div>